# Generated by Django 4.2.3 on 2024-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_alter_order_shippingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingPrice',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
