# Generated by Django 4.2.3 on 2024-02-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_alter_order_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
