# Generated by Django 4.2.9 on 2024-02-24 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_orderitem_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
